[package]
name = "mylib"
version = "0.1.0"
authors = ["johannesd3 <johannesd@outlook.com>"]
edition = "2018"
build = "build.rs"

[build-dependencies]
cbindgen = { version = "0.19", default-features = false }

[lib]
crate-type = ["cdylib"]
